### ISSUE TITLE
ansible-galaxy pull not updated

### ISSUE THREAD

**Issue by d-tork** [wilmardo/ansible-plex#14]
I don't know if you have any control over this, but I pulled from galaxy.ansible.com
```
$ ansible-galaxy install wilmardo.plex
```

and got this when I ran it:
```
TASK [wilmardo.plex : Add Plex apt repo (Ubuntu & Debian with systemd)] **********************
fatal: [maeve]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
```

When I inspected the file `~/.ansible/roles/wilmardo.plex/tasks/plex.yml` I noticed the apt_repository is different from what is currently in your github (notice the dot-slash, which  you fixed in bbf8f26): 
```yaml
    - name: Add Plex apt repo (Ubuntu & Debian with systemd)
      apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb/ ./public main
```

To fix it, I cloned directly from github. I'm just surprised that ansible-galaxy doesn't have these changes from 2019, wondering if you can update that? This is my first use of ansible roles and so it really threw me. For something that's supposed to save time, this cost me quite a bit and may affect someone else as well.
